In [1]:
import pandas as pd

# Ler o arquivo Excel em um DataFrame
df = pd.read_excel(r"C:\curso-eng-dados\Python-SGBDS\Origem de Dados\arquivos_excel\Produto.xlsx")

In [2]:
df.head(15)

    ID                  Nome  Price  Id_Category
0    0       Sapato vermelho     96            0
1    1  Bolsa mais que Velha   8000            0
2    2                 Calça     75            0
3    3    Camisa apertadinha    170            0
4    4   Vestido Super curto     57            0
5    5               Perfume     29            1
6    6      Creme de Barbear     15            1
7    7       Hidratante caro    800            1
8    8               Shampoo     15            1
9    9        Protetor Solar     11            1
10  10             Geladeira   1952            2
11  11                 Fogão   1373            2
12  12                    TV   1992            2
13  13      Máquina de Lavar   1826            2
14  14      Máquina de Secar   1774            2

In [3]:
#filtrar produto especifico metodo df.query()
dfsapatoroxo= df.query(' Nome == "Sapato Roxo" ')

In [4]:
dfsapatoroxo.head()

Empty DataFrame
Columns: [ID, Nome, Price, Id_Category]
Index: []

In [5]:
#varios produtos em uma lista (nome in ())
df.query("Nome in ('TV','Máquina de Secar','Shampoo')" )

    ID              Nome  Price  Id_Category
8    8           Shampoo     15            1
12  12                TV   1992            2
14  14  Máquina de Secar   1774            2

In [6]:
df.head(15)

    ID                  Nome  Price  Id_Category
0    0       Sapato vermelho     96            0
1    1  Bolsa mais que Velha   8000            0
2    2                 Calça     75            0
3    3    Camisa apertadinha    170            0
4    4   Vestido Super curto     57            0
5    5               Perfume     29            1
6    6      Creme de Barbear     15            1
7    7       Hidratante caro    800            1
8    8               Shampoo     15            1
9    9        Protetor Solar     11            1
10  10             Geladeira   1952            2
11  11                 Fogão   1373            2
12  12                    TV   1992            2
13  13      Máquina de Lavar   1826            2
14  14      Máquina de Secar   1774            2

In [7]:
#exemplo de valores
Valor1000= df.query('Price > 1000')

In [8]:
Valor1000.head(15)

    ID                  Nome  Price  Id_Category
1    1  Bolsa mais que Velha   8000            0
10  10             Geladeira   1952            2
11  11                 Fogão   1373            2
12  12                    TV   1992            2
13  13      Máquina de Lavar   1826            2
14  14      Máquina de Secar   1774            2
20  20               Ai-Fone   1720            4
21  21           Galáxia R10   2007            4
22  22            Chiai-homi   1152            4
23  23                 Ruaei   2795            4
24  24                Nóquia   2663            4

In [9]:
df.query('Price < 50')

    ID                  Nome  Price  Id_Category
5    5               Perfume     29            1
6    6      Creme de Barbear     15            1
8    8               Shampoo     15            1
9    9        Protetor Solar     11            1
15  15   O Romance Exagerado     46            3
16  16       Suspense Demais     42            3
17  17  Terror Aterrorizante     45            3
18  18   A Comédia Engraçada     20            3
19  19     A História de SQL     23            3
45  45          Futebol 2020     36            9
46  46                  Iôiô     16            9
47  47                  Peão     32            9
49  49     Casinha de Boneca     39            9

In [10]:
df.query('Price == 15')

   ID              Nome  Price  Id_Category
6   6  Creme de Barbear     15            1
8   8           Shampoo     15            1

In [11]:
clientes    = pd.read_csv  (r'C:\curso-eng-dados\Python-SGBDS\Origem de Dados\arquivos_csv\Clientes.csv',delimiter=',')
clientes.head(10)

,id,created_at,first_name,last_name,email,cell_phone,country,state,street,number,additionals
0,0,2017-11-01 14:45:41,Marta,Jesus,NaN,9 9102-7834,Brasil,Acre,NaN,NaN,Conjunto 16
1,1,2017-10-16 00:50:39,Luana,Almeida,NaN,9 7328-8718,Brasil,Rio Grande do Sul,Avenida 56 do Estado Rio Grande do Sul,989.0,Conjunto 17
2,2,2018-06-16 17:51:29,Frida,Mendes,frida@meu_email.com,9 5906-7552,Brasil,São Paulo,Avenida 59 do Estado São Paulo,534.0,NaN
3,3,2018-01-17 03:02:58,Daniela,Avelino,daniela@exemplo.com,9 4642-9486,Brasil,Mato Grosso,NaN,NaN,NaN
4,4,2018-08-06 07:24:16,Romário,Teixeira,NaN,9 3093-6522,Brasil,Bahia,Praça 56 do Estado Bahia,191.0,Apto 12
5,5,2018-01-05 17:20:49,Marcelo,Barroso,NaN,9 2830-2088,Brasil,Rio Grande do Sul,Rua 28 do Estado Rio Grande do Sul,805.0,Conjunto 13
6,6,2018-06-18 11:17:42,Cristiano,Elísio,cristiano@exemplo.com,9 3532-8404,Brasil,Goiás,Rua 78 do Estado Goiás,877.0,Apto 14
7,7,2018-02-08 12:36:09,Everton,Barbosa,everton@meu_email.com,9 2553-4087,Brasil,Distrito Federal,Avenida 86 do Estado Distrito Federal,864.0,Apto 14
8,8,2017-12-16 20:47:03,Gabriela,Alves,gabriela@exemplo.com,9 1353-8433,Brasil,Santa Catarina,NaN,NaN,NaN
9,9,2018-11-11 11:48:41,Luan,Dias,luan@exemplo.com,9 2417-3678,Brasil,Distrito Federal,Avenida 54 do Estado Distrito Federal,889.0,Conjunto 14

In [12]:
#filtrar ano e mes especifico diferente entre | e &

"""
| Pipe          = ou  ele obeder um criterio ou o outro e traz o resultado se tiver qualqer 1 criterio aceito
& E Comercial = retorna somente quando cumprir todos os criterios 
"""

'\n| Pipe          = ou  ele obeder um criterio ou o outro e traz o resultado se tiver qualqer 1 criterio aceito\n& E Comercial = retorna somente quando cumprir todos os criterios \n'

In [13]:
#varios produtos em uma lista (nome in ())  -- com variaveis de uma lista 
#criar uma lista de filtros ['lista separada por ,'] exemplo de filtrar estados Acre,Bahia,Goiás e depois somenente o primeiro nome @ faz a referencia
filtroestado=['Acre','Bahia','Goiás','Roraima']
clientes.query('state  in @filtroestado   | first_name ==  "Marta"   ')

,id,created_at,first_name,last_name,email,cell_phone,country,state,street,number,additionals
0,0,2017-11-01 14:45:41,Marta,Jesus,NaN,9 9102-7834,Brasil,Acre,NaN,NaN,Conjunto 16
4,4,2018-08-06 07:24:16,Romário,Teixeira,NaN,9 3093-6522,Brasil,Bahia,Praça 56 do Estado Bahia,191.0,Apto 12
6,6,2018-06-18 11:17:42,Cristiano,Elísio,cristiano@exemplo.com,9 3532-8404,Brasil,Goiás,Rua 78 do Estado Goiás,877.0,Apto 14
21,21,2018-02-21 15:35:55,Diego,Freire,diego@teste.com,9 6686-4094,Brasil,Bahia,Praça 4 do Estado Bahia,906.0,Apto 20
27,27,2018-11-08 11:12:47,Luan,Lima,luan@teste.com,9 2529-8197,Brasil,Acre,Praça 86 do Estado Acre,303.0,Apto 27
32,32,2018-07-22 11:59:27,Ana,Campos,ana@teste.com,9 1932-9841,Brasil,Bahia,Avenida 52 do Estado Bahia,402.0,NaN
34,34,2018-10-05 01:14:05,José,Campos,josé@teste.com,9 7552-4340,Brasil,Goiás,Praça 25 do Estado Goiás,884.0,Apto 7
37,37,2018-03-02 22:27:03,Daniela,Monteiro,daniela@meu_email.com,9 4704-5844,Brasil,Goiás,Rua 43 do Estado Goiás,116.0,Apto 28
42,42,2018-04-09 19:12:23,João,Almeida,joão@usuario.com,9 4650-1753,Brasil,Goiás,Praça 3 do Estado Goiás,986.0,Apto 9
52,52,2017-12-04 17:42:34,Bruno,Anjos,bruno@teste.com,9 3004-3740,Brasil,Goiás,Rua 53 do Estado Goiás,825.0,NaN
58,58,2018-09-13 03:13:02,Rafael,Rodrigues,rafael@meu_email.com,9 6550-3557,Brasil,Bahia,Praça 94 do Estado Bahia,647.0,Apto 25
75,75,2018-06-21 14:28:03,Marta,Abreu,NaN,9 9024-3467,Brasil,Roraima,Avenida 67 do Estado Roraima,410.0,Conjunto 23
77,77,2018-11-30 10:29:55,Ana,Monteiro,ana@teste.com,9 3871-4132,Brasil,Bahia,Praça 86 do Estado Bahia,604.0,Apto 30
86,86,2018-03-12 09:30:24,Adalberto,Oliveira,adalberto@teste.com,9 3081-3441,Brasil,Roraima,Rua 40 do Estado Roraima,401.0,Conjunto 17
87,87,2018-08-16 20:25:23,Beatriz,Abreu,beatriz@usuario.com,9 2254-6798,Brasil,Acre,Rua 95 do Estado Acre,482.0,Conjunto 16
89,89,2017-12-07 19:24:54,Daniela,Pires,daniela@usuario.com,9 6666-2265,Brasil,Bahia,Rua 31 do Estado Bahia,441.0,NaN
92,92,2017-10-16 16:29:15,Beatriz,Bueno,beatriz@teste.com,9 4435-2960,Brasil,Acre,Rua 71 do Estado Acre,978.0,Apto 24
97,97,2018-07-04 18:45:41,Marta,Góes,marta@teste.com,9 4102-4352,Brasil,Paraná,Rua 61 do Estado Paraná,402.0,Apto 24

Datas na Query

In [14]:
import pandas as pd

In [15]:
clientes    = pd.read_csv  (r'C:\curso-eng-dados\Python-SGBDS\Origem de Dados\arquivos_csv\Clientes.csv',delimiter=',')
clientes.head(10)

,id,created_at,first_name,last_name,email,cell_phone,country,state,street,number,additionals
0,0,2017-11-01 14:45:41,Marta,Jesus,NaN,9 9102-7834,Brasil,Acre,NaN,NaN,Conjunto 16
1,1,2017-10-16 00:50:39,Luana,Almeida,NaN,9 7328-8718,Brasil,Rio Grande do Sul,Avenida 56 do Estado Rio Grande do Sul,989.0,Conjunto 17
2,2,2018-06-16 17:51:29,Frida,Mendes,frida@meu_email.com,9 5906-7552,Brasil,São Paulo,Avenida 59 do Estado São Paulo,534.0,NaN
3,3,2018-01-17 03:02:58,Daniela,Avelino,daniela@exemplo.com,9 4642-9486,Brasil,Mato Grosso,NaN,NaN,NaN
4,4,2018-08-06 07:24:16,Romário,Teixeira,NaN,9 3093-6522,Brasil,Bahia,Praça 56 do Estado Bahia,191.0,Apto 12
5,5,2018-01-05 17:20:49,Marcelo,Barroso,NaN,9 2830-2088,Brasil,Rio Grande do Sul,Rua 28 do Estado Rio Grande do Sul,805.0,Conjunto 13
6,6,2018-06-18 11:17:42,Cristiano,Elísio,cristiano@exemplo.com,9 3532-8404,Brasil,Goiás,Rua 78 do Estado Goiás,877.0,Apto 14
7,7,2018-02-08 12:36:09,Everton,Barbosa,everton@meu_email.com,9 2553-4087,Brasil,Distrito Federal,Avenida 86 do Estado Distrito Federal,864.0,Apto 14
8,8,2017-12-16 20:47:03,Gabriela,Alves,gabriela@exemplo.com,9 1353-8433,Brasil,Santa Catarina,NaN,NaN,NaN
9,9,2018-11-11 11:48:41,Luan,Dias,luan@exemplo.com,9 2417-3678,Brasil,Distrito Federal,Avenida 54 do Estado Distrito Federal,889.0,Conjunto 14

In [16]:
clientes.dtypes

id               int64
created_at      object
first_name      object
last_name       object
email           object
cell_phone      object
country         object
state           object
street          object
number         float64
additionals     object
dtype: object

In [17]:
# Converter a coluna 'data' para o tipo de dados datetime, se ainda não estiver(para funcionar na query tem que estar nesse formato de data)
clientes['created_at'] = pd.to_datetime(clientes['created_at'])

In [18]:
clientes.head()

,id,created_at,first_name,last_name,email,cell_phone,country,state,street,number,additionals
0,0,2017-11-01 14:45:41,Marta,Jesus,NaN,9 9102-7834,Brasil,Acre,NaN,NaN,Conjunto 16
1,1,2017-10-16 00:50:39,Luana,Almeida,NaN,9 7328-8718,Brasil,Rio Grande do Sul,Avenida 56 do Estado Rio Grande do Sul,989.0,Conjunto 17
2,2,2018-06-16 17:51:29,Frida,Mendes,frida@meu_email.com,9 5906-7552,Brasil,São Paulo,Avenida 59 do Estado São Paulo,534.0,NaN
3,3,2018-01-17 03:02:58,Daniela,Avelino,daniela@exemplo.com,9 4642-9486,Brasil,Mato Grosso,NaN,NaN,NaN
4,4,2018-08-06 07:24:16,Romário,Teixeira,NaN,9 3093-6522,Brasil,Bahia,Praça 56 do Estado Bahia,191.0,Apto 12

In [19]:
#clientes['ano']=clientes['created_at'].dt.year

In [20]:
# filtrando 1 ano especifico 
clientes.query('created_at.dt.year  == 2017')

,id,created_at,first_name,last_name,email,cell_phone,country,state,street,number,additionals
0,0,2017-11-01 14:45:41,Marta,Jesus,NaN,9 9102-7834,Brasil,Acre,NaN,NaN,Conjunto 16
1,1,2017-10-16 00:50:39,Luana,Almeida,NaN,9 7328-8718,Brasil,Rio Grande do Sul,Avenida 56 do Estado Rio Grande do Sul,989.0,Conjunto 17
8,8,2017-12-16 20:47:03,Gabriela,Alves,gabriela@exemplo.com,9 1353-8433,Brasil,Santa Catarina,NaN,NaN,NaN
10,10,2017-12-16 15:41:00,Mariana,Alves,mariana@meu_email.com,9 1846-6377,Brasil,Santa Catarina,NaN,NaN,NaN
14,14,2017-11-12 03:02:41,Francisco,Nascimento,francisco@exemplo.com,9 7264-9020,Brasil,Distrito Federal,Rua 75 do Estado Distrito Federal,47.0,NaN
16,16,2017-12-12 21:29:54,Laura,Santos,laura@exemplo.com,9 7802-6152,Brasil,Maranhão,Rua 57 do Estado Maranhão,213.0,NaN
17,17,2017-10-19 20:18:14,João,Magalhães,joão@exemplo.com,9 5995-1272,Brasil,Pernambuco,Rua 20 do Estado Pernambuco,781.0,Apto 17
20,20,2017-12-22 10:51:28,Adalberto,Silva,adalberto@usuario.com,9 1338-1447,Brasil,São Paulo,Rua 57 do Estado São Paulo,851.0,Conjunto 20
23,23,2017-10-26 00:35:22,Maria,Pires,NaN,9 8229-1067,Brasil,Amazonas,Avenida 80 do Estado Amazonas,581.0,NaN
28,28,2017-11-26 05:17:39,Beatriz,Araújo,beatriz@usuario.com,9 4543-3853,Brasil,Minas Gerais,Praça 7 do Estado Minas Gerais,536.0,Conjunto 5
33,33,2017-12-28 12:51:34,João,da Silva,joão@usuario.com,9 2813-8103,Brasil,Paraná,Avenida 27 do Estado Paraná,240.0,Apto 6
39,39,2017-11-15 07:17:25,Caio,Batista,caio@usuario.com,9 4761-6542,Brasil,Maranhão,Avenida 87 do Estado Maranhão,656.0,Apto 25
51,51,2017-12-26 15:38:15,Caio,Mendes,caio@teste.com,9 6437-5008,Brasil,Pernambuco,Rua 34 do Estado Pernambuco,931.0,NaN
52,52,2017-12-04 17:42:34,Bruno,Anjos,bruno@teste.com,9 3004-3740,Brasil,Goiás,Rua 53 do Estado Goiás,825.0,NaN
56,56,2017-12-01 22:40:40,Cristiano,Fagundes,cristiano@usuario.com,9 7680-6400,Brasil,Piauí,Avenida 20 do Estado Piauí,236.0,Apto 30
59,59,2017-12-03 16:24:32,Stephanie,Freire,stephanie@usuario.com,9 3256-1853,Brasil,São Paulo,Rua 52 do Estado São Paulo,34.0,Apto 24
70,70,2017-10-22 12:49:39,Diego,Barboza,NaN,9 4849-7409,Brasil,Mato Grosso do Sul,Avenida 3 do Estado Mato Grosso do Sul,250.0,NaN
71,71,2017-12-12 16:16:52,Gerson,Barroso,gerson@exemplo.com,9 5719-4227,Brasil,Pernambuco,NaN,NaN,Apto 2
78,78,2017-11-02 22:13:22,Laura,Queiroz,laura@exemplo.com,9 6338-8617,Brasil,São Paulo,Praça 19 do Estado São Paulo,878.0,Conjunto 3
79,79,2017-12-13 08:41:05,Hélen,Souza,hélen@teste.com,9 9974-1066,Brasil,Paraná,Avenida 20 do Estado Paraná,661.0,Conjunto 13
85,85,2017-11-24 12:44:36,Eduardo,Teixeira,NaN,9 2537-7930,Brasil,Rio Grande do Norte,NaN,NaN,NaN
88,88,2017-10-12 15:17:05,Rafael,Batista,rafael@usuario.com,9 8656-5668,Brasil,Ceará,Rua 78 do Estado Ceará,787.0,Apto 3
89,89,2017-12-07 19:24:54,Daniela,Pires,daniela@usuario.com,9 6666-2265,Brasil,Bahia,Rua 31 do Estado Bahia,441.0,NaN
90,90,2017-12-16 22:14:58,Stephanie,Rosa,NaN,9 3040-4414,Brasil,Rio Grande do Norte,NaN,NaN,NaN
92,92,2017-10-16 16:29:15,Beatriz,Bueno,beatriz@teste.com,9 4435-2960,Brasil,Acre,Rua 71 do Estado Acre,978.0,Apto 24

In [21]:
mesdez = clientes.query('created_at.dt.month  == 10')

In [22]:
#exemplo ano 2017 e mes 10
clientes.query('created_at.dt.year == 2017  &  created_at.dt.month  == 10 ')

,id,created_at,first_name,last_name,email,cell_phone,country,state,street,number,additionals
1,1,2017-10-16 00:50:39,Luana,Almeida,NaN,9 7328-8718,Brasil,Rio Grande do Sul,Avenida 56 do Estado Rio Grande do Sul,989.0,Conjunto 17
17,17,2017-10-19 20:18:14,João,Magalhães,joão@exemplo.com,9 5995-1272,Brasil,Pernambuco,Rua 20 do Estado Pernambuco,781.0,Apto 17
23,23,2017-10-26 00:35:22,Maria,Pires,NaN,9 8229-1067,Brasil,Amazonas,Avenida 80 do Estado Amazonas,581.0,NaN
70,70,2017-10-22 12:49:39,Diego,Barboza,NaN,9 4849-7409,Brasil,Mato Grosso do Sul,Avenida 3 do Estado Mato Grosso do Sul,250.0,NaN
88,88,2017-10-12 15:17:05,Rafael,Batista,rafael@usuario.com,9 8656-5668,Brasil,Ceará,Rua 78 do Estado Ceará,787.0,Apto 3
92,92,2017-10-16 16:29:15,Beatriz,Bueno,beatriz@teste.com,9 4435-2960,Brasil,Acre,Rua 71 do Estado Acre,978.0,Apto 24

In [23]:
#exemplo ano 2017 ou mes 10 (simulando obedecendo ou 1 criterio ouo outro) fique atento com e ou ou 
clientes.query('created_at.dt.year == 2017  |  created_at.dt.month  == 10 ')

,id,created_at,first_name,last_name,email,cell_phone,country,state,street,number,additionals
0,0,2017-11-01 14:45:41,Marta,Jesus,NaN,9 9102-7834,Brasil,Acre,NaN,NaN,Conjunto 16
1,1,2017-10-16 00:50:39,Luana,Almeida,NaN,9 7328-8718,Brasil,Rio Grande do Sul,Avenida 56 do Estado Rio Grande do Sul,989.0,Conjunto 17
8,8,2017-12-16 20:47:03,Gabriela,Alves,gabriela@exemplo.com,9 1353-8433,Brasil,Santa Catarina,NaN,NaN,NaN
10,10,2017-12-16 15:41:00,Mariana,Alves,mariana@meu_email.com,9 1846-6377,Brasil,Santa Catarina,NaN,NaN,NaN
14,14,2017-11-12 03:02:41,Francisco,Nascimento,francisco@exemplo.com,9 7264-9020,Brasil,Distrito Federal,Rua 75 do Estado Distrito Federal,47.0,NaN
16,16,2017-12-12 21:29:54,Laura,Santos,laura@exemplo.com,9 7802-6152,Brasil,Maranhão,Rua 57 do Estado Maranhão,213.0,NaN
17,17,2017-10-19 20:18:14,João,Magalhães,joão@exemplo.com,9 5995-1272,Brasil,Pernambuco,Rua 20 do Estado Pernambuco,781.0,Apto 17
19,19,2018-10-20 19:31:52,Caíque,Monteiro,caíque@exemplo.com,9 9793-9986,Brasil,Piauí,NaN,NaN,Conjunto 13
20,20,2017-12-22 10:51:28,Adalberto,Silva,adalberto@usuario.com,9 1338-1447,Brasil,São Paulo,Rua 57 do Estado São Paulo,851.0,Conjunto 20
23,23,2017-10-26 00:35:22,Maria,Pires,NaN,9 8229-1067,Brasil,Amazonas,Avenida 80 do Estado Amazonas,581.0,NaN
28,28,2017-11-26 05:17:39,Beatriz,Araújo,beatriz@usuario.com,9 4543-3853,Brasil,Minas Gerais,Praça 7 do Estado Minas Gerais,536.0,Conjunto 5
33,33,2017-12-28 12:51:34,João,da Silva,joão@usuario.com,9 2813-8103,Brasil,Paraná,Avenida 27 do Estado Paraná,240.0,Apto 6
34,34,2018-10-05 01:14:05,José,Campos,josé@teste.com,9 7552-4340,Brasil,Goiás,Praça 25 do Estado Goiás,884.0,Apto 7
39,39,2017-11-15 07:17:25,Caio,Batista,caio@usuario.com,9 4761-6542,Brasil,Maranhão,Avenida 87 do Estado Maranhão,656.0,Apto 25
51,51,2017-12-26 15:38:15,Caio,Mendes,caio@teste.com,9 6437-5008,Brasil,Pernambuco,Rua 34 do Estado Pernambuco,931.0,NaN
52,52,2017-12-04 17:42:34,Bruno,Anjos,bruno@teste.com,9 3004-3740,Brasil,Goiás,Rua 53 do Estado Goiás,825.0,NaN
56,56,2017-12-01 22:40:40,Cristiano,Fagundes,cristiano@usuario.com,9 7680-6400,Brasil,Piauí,Avenida 20 do Estado Piauí,236.0,Apto 30
59,59,2017-12-03 16:24:32,Stephanie,Freire,stephanie@usuario.com,9 3256-1853,Brasil,São Paulo,Rua 52 do Estado São Paulo,34.0,Apto 24
64,64,2018-10-30 15:47:32,Luan,Ramos,luan@exemplo.com,9 6843-3876,Brasil,Pernambuco,Rua 63 do Estado Pernambuco,345.0,Conjunto 10
66,66,2018-10-18 04:31:59,Stephanie,Abreu,stephanie@meu_email.com,9 6466-2389,Brasil,Mato Grosso,Rua 19 do Estado Mato Grosso,53.0,Conjunto 13
70,70,2017-10-22 12:49:39,Diego,Barboza,NaN,9 4849-7409,Brasil,Mato Grosso do Sul,Avenida 3 do Estado Mato Grosso do Sul,250.0,NaN
71,71,2017-12-12 16:16:52,Gerson,Barroso,gerson@exemplo.com,9 5719-4227,Brasil,Pernambuco,NaN,NaN,Apto 2
78,78,2017-11-02 22:13:22,Laura,Queiroz,laura@exemplo.com,9 6338-8617,Brasil,São Paulo,Praça 19 do Estado São Paulo,878.0,Conjunto 3
79,79,2017-12-13 08:41:05,Hélen,Souza,hélen@teste.com,9 9974-1066,Brasil,Paraná,Avenida 20 do Estado Paraná,661.0,Conjunto 13
80,80,2018-10-10 00:06:32,Daniela,Góes,daniela@usuario.com,9 5394-6677,Brasil,Alagoas,Praça 22 do Estado Alagoas,235.0,NaN
85,85,2017-11-24 12:44:36,Eduardo,Teixeira,NaN,9 2537-7930,Brasil,Rio Grande do Norte,NaN,NaN,NaN
88,88,2017-10-12 15:17:05,Rafael,Batista,rafael@usuario.com,9 8656-5668,Brasil,Ceará,Rua 78 do Estado Ceará,787.0,Apto 3
89,89,2017-12-07 19:24:54,Daniela,Pires,daniela@usuario.com,9 6666-2265,Brasil,Bahia,Rua 31 do Estado Bahia,441.0,NaN
90,90,2017-12-16 22:14:58,Stephanie,Rosa,NaN,9 3040-4414,Brasil,Rio Grande do Norte,NaN,NaN,NaN
92,92,2017-10-16 16:29:15,Beatriz,Bueno,beatriz@teste.com,9 4435-2960,Brasil,Acre,Rua 71 do Estado Acre,978.0,Apto 24
94,94,2018-10-29 11:39:58,Cristiano,Pereira,cristiano@meu_email.com,9 4404-8717,Brasil,Piauí,Praça 100 do Estado Piauí,809.0,NaN
95,95,2018-10-01 11:35:59,Mariana,Rosa,mariana@usuario.com,9 3139-2145,Brasil,NaN,NaN,NaN,NaN

#### Ano e mes Atual

In [24]:
from datetime import datetime
import pandas  as pd

In [25]:
ordens    = pd.read_excel(r'C:\curso-eng-dados\Python-SGBDS\Origem de Dados\arquivos_excel\Ordens.xlsx')
ordens.head()

   id          created_at  customer_id              status
0   0 2019-08-28 03:36:31           91            entregue
1   1 2019-08-16 20:21:30            7            entregue
2   2 2019-07-11 11:00:06           26  pagamento_pendente
3   3 2019-08-27 21:04:41           92  pagamento_pendente
4   4 2019-11-03 19:58:37           63    entrega_pendente

In [26]:
# mes e ano atual
data_atual=datetime.now()
ano_atual = datetime.now().year  #traz o ano atual
mes_atual = datetime.now().month # traz o mes atual

In [27]:
# Filtrando mes e ano atual de um Df

ordens.query('created_at.dt.year == @ano_atual   &  created_at.dt.month ==  @mes_atual')

        id          created_at  customer_id              status
1400  1400 2025-06-21 16:00:00           49    entrega_pendente
1401  1401 2025-06-24 10:35:00           62    entrega_pendente
1415  1415 2025-06-24 10:35:00           52    entrega_pendente
1427  1427 2025-06-24 10:35:00           71            entregue
1455  1455 2025-06-24 10:35:00           66            carrinho
1480  1480 2025-06-24 10:35:00           53  pagamento_pendente
1504  1504 2025-06-24 10:35:00           88    entrega_pendente
1553  1553 2025-06-24 10:35:00           18  pagamento_pendente
1581  1581 2025-06-24 10:35:00            0    entrega_pendente
1608  1608 2025-06-24 10:35:00           75            entregue
1632  1632 2025-06-24 10:35:00           61            entregue
1674  1674 2025-06-24 10:35:00           82            carrinho
1722  1722 2025-06-24 10:35:00           71  pagamento_pendente
1770  1770 2025-06-24 10:35:00           61           cancelado
1793  1793 2025-06-21 16:00:00           29            entregue
1797  1797 2025-06-24 10:35:00           16            entregue
1804  1804 2025-06-21 16:00:00            6            entregue
1835  1835 2025-06-24 10:35:00           57            carrinho
1843  1843 2025-06-24 10:35:00           77            carrinho
1844  1844 2025-06-24 10:35:00           18  pagamento_pendente
1845  1845 2025-06-24 10:35:00           76            entregue
1867  1867 2025-06-24 10:35:00           84            entregue
1869  1869 2025-06-24 10:35:00           80  pagamento_pendente
1870  1870 2025-06-24 10:35:00           51    entrega_pendente
2527  2527 2025-06-21 16:00:00           10            carrinho
2554  2554 2025-06-21 16:00:00           31            carrinho
2590  2590 2025-06-21 16:00:00           94            carrinho
2598  2598 2025-06-21 16:00:00            5  pagamento_pendente
5020  5020 2025-06-21 16:00:00           87            carrinho
5028  5028 2025-06-21 16:00:00           93  pagamento_pendente
5034  5034 2025-06-21 16:00:00           23  pagamento_pendente
5045  5045 2025-06-21 16:00:00           30            entregue
8163  8163 2025-06-21 16:00:00           97  pagamento_pendente
8164  8164 2025-06-21 16:00:00           47    entrega_pendente
8165  8165 2025-06-21 16:00:00           28            carrinho
8166  8166 2025-06-21 16:00:00           34            entregue
8167  8167 2025-06-21 16:00:00           36            entregue
8249  8249 2025-06-21 16:00:00           79            carrinho
8256  8256 2025-06-21 16:00:00            2            entregue
8276  8276 2025-06-21 16:00:00           48           cancelado