In [54]:
import pandas as pd
from google.cloud import bigquery
from google.oauth2 import service_account
from pandas_gbq import to_gbq
from datetime import datetime

In [55]:
df = pd.read_excel(r"C:\curso-eng-dados\Python-SGBDS\Origem de Dados\arquivos_excel\Produto.xlsx")

In [56]:
df['DataHoraCarga'] = datetime.now()

In [57]:
df.head()

   ID                  Nome  Price  Id_Category              DataHoraCarga
0   0       Sapato vermelho     96            0 2025-06-24 08:57:42.915251
1   1  Bolsa mais que Velha   8000            0 2025-06-24 08:57:42.915251
2   2                 Calça     75            0 2025-06-24 08:57:42.915251
3   3    Camisa apertadinha    170            0 2025-06-24 08:57:42.915251
4   4   Vestido Super curto     57            0 2025-06-24 08:57:42.915251

In [58]:
df['DataHoraCarga'] = datetime.now().strftime('%Y-%m-%d %H:%M:%S') # precisa dessa conversão para o bigquery aceitar

In [59]:
df.head()

   ID                  Nome  Price  Id_Category        DataHoraCarga
0   0       Sapato vermelho     96            0  2025-06-24 08:57:42
1   1  Bolsa mais que Velha   8000            0  2025-06-24 08:57:42
2   2                 Calça     75            0  2025-06-24 08:57:42
3   3    Camisa apertadinha    170            0  2025-06-24 08:57:42
4   4   Vestido Super curto     57            0  2025-06-24 08:57:42

In [60]:
df['DataCarga'] = datetime.now().date()

In [61]:
df.head()

,ID,Nome,Price,Id_Category,DataHoraCarga,DataCarga
0,0,Sapato vermelho,96,0,2025-06-24 08:57:42,2025-06-24
1,1,Bolsa mais que Velha,8000,0,2025-06-24 08:57:42,2025-06-24
2,2,Calça,75,0,2025-06-24 08:57:42,2025-06-24
3,3,Camisa apertadinha,170,0,2025-06-24 08:57:42,2025-06-24
4,4,Vestido Super curto,57,0,2025-06-24 08:57:42,2025-06-24

In [62]:
df['DataHoraCargaPTBR'] = datetime.now().strftime('%d/%M/%Y')

In [63]:
df.head()

,ID,Nome,Price,Id_Category,DataHoraCarga,DataCarga,DataHoraCargaPTBR
0,0,Sapato vermelho,96,0,2025-06-24 08:57:42,2025-06-24,24/57/2025
1,1,Bolsa mais que Velha,8000,0,2025-06-24 08:57:42,2025-06-24,24/57/2025
2,2,Calça,75,0,2025-06-24 08:57:42,2025-06-24,24/57/2025
3,3,Camisa apertadinha,170,0,2025-06-24 08:57:42,2025-06-24,24/57/2025
4,4,Vestido Super curto,57,0,2025-06-24 08:57:42,2025-06-24,24/57/2025

In [64]:
df['HoraCarga'] = datetime.now().strftime('%H:%M:%S')

In [65]:
df.head()

,ID,Nome,Price,Id_Category,DataHoraCarga,DataCarga,DataHoraCargaPTBR,HoraCarga
0,0,Sapato vermelho,96,0,2025-06-24 08:57:42,2025-06-24,24/57/2025,08:57:42
1,1,Bolsa mais que Velha,8000,0,2025-06-24 08:57:42,2025-06-24,24/57/2025,08:57:42
2,2,Calça,75,0,2025-06-24 08:57:42,2025-06-24,24/57/2025,08:57:42
3,3,Camisa apertadinha,170,0,2025-06-24 08:57:42,2025-06-24,24/57/2025,08:57:42
4,4,Vestido Super curto,57,0,2025-06-24 08:57:42,2025-06-24,24/57/2025,08:57:42

In [66]:
df.dtypes

ID                    int64
Nome                 object
Price                 int64
Id_Category           int64
DataHoraCarga        object
DataCarga            object
DataHoraCargaPTBR    object
HoraCarga            object
dtype: object

In [67]:
#converter para BQ Aceitar
df['DataHoraCarga'] = pd.to_datetime(df['DataHoraCarga'])
df['DataCarga'] = pd.to_datetime(df['DataCarga'])

In [68]:
df.dtypes

ID                            int64
Nome                         object
Price                         int64
Id_Category                   int64
DataHoraCarga        datetime64[ns]
DataCarga            datetime64[ns]
DataHoraCargaPTBR            object
HoraCarga                    object
dtype: object

In [69]:
df.head()

,ID,Nome,Price,Id_Category,DataHoraCarga,DataCarga,DataHoraCargaPTBR,HoraCarga
0,0,Sapato vermelho,96,0,2025-06-24 08:57:42,2025-06-24,24/57/2025,08:57:42
1,1,Bolsa mais que Velha,8000,0,2025-06-24 08:57:42,2025-06-24,24/57/2025,08:57:42
2,2,Calça,75,0,2025-06-24 08:57:42,2025-06-24,24/57/2025,08:57:42
3,3,Camisa apertadinha,170,0,2025-06-24 08:57:42,2025-06-24,24/57/2025,08:57:42
4,4,Vestido Super curto,57,0,2025-06-24 08:57:42,2025-06-24,24/57/2025,08:57:42

In [70]:
# Credencias para validar importar dados para o google bigquery
credencial = r'C:\curso-eng-dados\Python-SGBDS\Origem de Dados\pythoncurso-462414-f5463d5035ab.json'
CredImportacao = service_account.Credentials.from_service_account_file(
  credencial,
  scopes=['https://www.googleapis.com/auth/bigquery']
)

# Variaveis do projeto

projeto     = 'pythoncurso-462414'
dataset     = 'AulaPython'
tabela      = 'ProdutoHistorico'
parametro   = 'append'

# Replace = substituir a antiga pela original
# Append  = adiciona dados no fim da tabela

In [71]:
df.dtypes

ID                            int64
Nome                         object
Price                         int64
Id_Category                   int64
DataHoraCarga        datetime64[ns]
DataCarga            datetime64[ns]
DataHoraCargaPTBR            object
HoraCarga                    object
dtype: object

In [72]:
schema = [
    {'name': 'DataHoraCarga', 'type': 'TIMESTAMP'},# Use 'TIMESTAMP' para datetime64[ns] (pode ser tambem da certo)
    {'name': 'Price', 'type': 'INTEGER'},
    {'name': 'Id_Category', 'type': 'INTEGER'},
    {'name': 'DataCarga', 'type': 'DATE'} #SOMENTE DATA
]

In [73]:
# Use o método to_gbq para enviar o dataframe para o Bigquery
df.to_gbq(destination_table=f'{projeto}.{dataset}.{tabela}',
  project_id=projeto,
  if_exists=parametro,
  credentials=CredImportacao,
  table_schema=schema
  )

C:\Users\guspe\AppData\Local\Temp\ipykernel_9708\979740825.py:2: FutureWarning: to_gbq is deprecated and will be removed in a future version. Please use pandas_gbq.to_gbq instead: https://pandas-gbq.readthedocs.io/en/latest/api.html#pandas_gbq.to_gbq
  df.to_gbq(destination_table=f'{projeto}.{dataset}.{tabela}',

In [74]:
"""

SELECT * FROM `pythoncurso-398511.AulaPython.ProdutoHistorico`
where HoraCarga = 
  (SELECT max(HoraCarga)FROM `pythoncurso-398511.AulaPython.ProdutoHistorico`)

"""

'\n\nSELECT * FROM `pythoncurso-398511.AulaPython.ProdutoHistorico`\nwhere HoraCarga = \n  (SELECT max(HoraCarga)FROM `pythoncurso-398511.AulaPython.ProdutoHistorico`)\n\n'