https://requests.readthedocs.io/en/latest/api/

https://requests.readthedocs.io/en/latest/

https://www.postman.com/

https://servicodados.ibge.gov.br/api/docs/

In [ ]:
#pip install requests
#pip install --upgrade requests

In [1]:
import requests
url = "https://servicodados.ibge.gov.br/api/v1/localidades/estados"
response = requests.get(url)
print(response)

<Response [200]>

In [ ]:
"""
GET = Solicitar dados 
POST= Enviar dados 
PUT = atualizar um recurso existente ou criar um novo recurso se ele não existir
DELETE = Excluir 
PATCH  = aplicar modificações parciais a um recurso.

"""

In [3]:
# Mapeamento de códigos de status HTTP para seus respectivos nomes
codigo_para_nome = {
    100: 'continuar',
    101: 'mudando_protocolos',
    102: 'processando',
    103: 'checkpoint',
    122: 'uri_muito_longa',  # ou 'pedido_uri_muito_longo'
    200: 'ok',  # ou 'certo', 'tudo_certo', 'tudo_bem', '\o/', '✓'
    201: 'criado',
    202: 'aceito',
    203: 'informacao_nao_autoritativa',  # ou 'informacao_nao_autorizada'
    204: 'sem_conteudo',
    205: 'conteudo_redefinido',  # ou 'redefinir'
    206: 'conteudo_parcial',  # ou 'parcial'
    207: 'multi_status',  # ou 'status_multiplas', 'multi_stati', 'status_multiplos'
    208: 'ja_reportado',
    226: 'im_usado',
    300: 'escolhas_multiplas',
    301: 'movido_permanentemente',  # ou 'movido', '\o-'
    302: 'encontrado',
    303: 'ver_outro',  # ou 'outro'
    304: 'nao_modificado',
    305: 'usar_proxy',
    306: 'trocar_proxy',
    307: 'redirecionamento_temporario',  # ou 'mover_temporario', 'temporario'
    308: 'redirecionamento_permanente',  # ou 'continuar_incompleto', 'continuar'
    400: 'requisicao_invalida',  # ou 'ruim'
    401: 'nao_autorizado',
    402: 'pagamento_necessario',  # ou 'pagamento'
    403: 'proibido',
    404: 'nao_encontrado',  # ou '-o-'
    405: 'metodo_nao_permitido',  # ou 'nao_permitido'
    406: 'nao_aceitavel',
    407: 'autenticacao_proxy_necessaria',  # ou 'proxy_auth', 'autenticacao_proxy'
    408: 'tempo_esgotado_requisicao',  # ou 'tempo_esgotado'
    409: 'conflito',
    410: 'desaparecido',
    411: 'tamanho_necessario',
    412: 'pre_condicao_falhou',  # ou 'pre_condicao'
    413: 'entidade_requisicao_grande',
    414: 'uri_requisicao_grande',
    415: 'tipo_midia_nao_suportado',  # ou 'midia_nao_suportada', 'tipo_midia'
    416: 'intervalo_requisitado_nao_satisfatorio',  # ou 'intervalo_requisitado', 'intervalo_nao_satisfatorio'
    417: 'expectativa_falhou',
    418: 'sou_um_bule',  # ou 'bule', 'eu_sou_um_bule'
    421: 'requisicao_errada',
    422: 'entidade_nao_processavel',  # ou 'nao_processavel'
    423: 'trancado',
    424: 'dependencia_falhou',  # ou 'falha_dependencia'
    425: 'colecao_desordenada',  # ou 'desordenada', 'muito_cedo'
    426: 'atualizacao_necessaria',  # ou 'atualizacao'
    428: 'pre_condicao_necessaria',  # ou 'pre_condicao'
    429: 'muitas_requisicoes',  # ou 'muitas'
    431: 'campos_cabecalho_grandes',  # ou 'campos_grandes'
    444: 'sem_resposta',  # ou 'nenhum'
    449: 'tentar_com',  # ou 'tentar'
    450: 'bloqueado_por_controles_parentais_windows',  # ou 'controles_parentais'
    451: 'indisponivel_por_motivos_legais',  # ou 'motivos_legais'
    499: 'cliente_fechou_requisicao',
    500: 'erro_servidor_interno',  # ou 'erro_servidor', '/o\\', '✗'
    501: 'nao_implementado',
    502: 'bad_gateway',
    503: 'servico_indisponivel',  # ou 'indisponivel'
    504: 'tempo_esgotado_gateway',
    505: 'versao_http_nao_suportada',  # ou 'versao_http'
    506: 'variante_negocia_tambem',
    507: 'armazenamento_insuficiente',
    509: 'limite_banda_excedido',  # ou 'banda'
    510: 'nao_extendido',
    511: 'autenticacao_rede_necessaria',  # ou 'autenticacao_rede'
}

# Exemplo de uso:
print(codigo_para_nome[450])

bloqueado_por_controles_parentais_windows

In [ ]:
import requests
url = "https://servicodados.ibge.gov.br/api/v1/localidades/estados"
response = requests.get(url)

data = response.json()
data

Transformando dados Json em um DF

In [6]:
import requests
import pandas as pd

url = "https://servicodados.ibge.gov.br/api/v1/localidades/estados"
response = requests.get(url)

data = response.json()

df = pd.DataFrame(data)
df.head()

   id sigla      nome                                    regiao
0  11    RO  Rondônia  {'id': 1, 'sigla': 'N', 'nome': 'Norte'}
1  12    AC      Acre  {'id': 1, 'sigla': 'N', 'nome': 'Norte'}
2  13    AM  Amazonas  {'id': 1, 'sigla': 'N', 'nome': 'Norte'}
3  14    RR   Roraima  {'id': 1, 'sigla': 'N', 'nome': 'Norte'}
4  15    PA      Pará  {'id': 1, 'sigla': 'N', 'nome': 'Norte'}

Transformando em DF e normalizando dados

In [7]:
import requests
import pandas as pd

url = "https://servicodados.ibge.gov.br/api/v1/localidades/estados"
response = requests.get(url)

data = response.json()

df = pd.json_normalize(data)
df.head()

   id sigla      nome  regiao.id regiao.sigla regiao.nome
0  11    RO  Rondônia          1            N       Norte
1  12    AC      Acre          1            N       Norte
2  13    AM  Amazonas          1            N       Norte
3  14    RR   Roraima          1            N       Norte
4  15    PA      Pará          1            N       Norte